### PR TITLE
Organize core dev tech by year

### PR DESCRIPTION
**Pull request by josibake**
I tried running the `/.preview_branch.sh` script in the bitcointranscripts.github.io repo, but it doesnt seem to be pulling in my content.

Will fiddle with it more for later, but opening the PR for now in case someone more familiar with this repo has pointers.

### CODE REVIEW

**Comment by josibake** [comment]
@kouloumos any pointers?

**Comment by kouloumos** [comment]
It seem that you caught an edge case that I didn't test. Before running preview, you should first run `git submodule update --init`, so in your case is:
```
git submodule update --init
./preview_branch.sh josibake organize-core-dev-tech-by-year
```

For your changes to work, you'll need to also [add an `_index.md` in each new directory](https://github.com/bitcointranscripts/bitcointranscripts#contribution). Also, because the name of the directory will be in the resulting url, maybe you should consider an only-date naming scheme?, e.g `bitcoin-core-dev-tech/2018-03` instead of  `bitcoin-core-dev-tech/bitcoin-coredev-2018-03`. I know that the 2015 directory already follows this naming scheme, but maybe this is an opportunity to also simplify that one (aliases included).

**Comment by josibake** [comment]
> It seem that you caught an edge case that I didn't test. Before running preview, you should first run `git submodule update --init`

This worked, thanks!

> For your changes to work, you'll need to also `_index.md`

Done!

> maybe you should consider an only-date naming scheme?, e.g `bitcoin-core-dev-tech/2018-03` instead of `bitcoin-core-dev-tech/bitcoin-coredev-2018-03`. I know that the 2015 directory already follows this naming scheme, but maybe this is an opportunity to also simplify that one (aliases included).

Agree, this is much nicer. Added!

I'm not sure if I did the aliases right for the ES pages, but from local testing everything seemed to work.

**Review by kouloumos — COMMENTED** [review]
It looks good, thank you for doing this @josibake! I left some minor comments about the spanish aliases as well as an improvement on how the new pages are displayed.

**Pull request merged**
