### PR TITLE
Add assume-utxo to chaincode-labs/chaincode-podcast

### PR DESCRIPTION
**Pull request by Numba1ne**
This PR adds [Assume UTXO](https://www.youtube.com/watch?v=knBHvzKsIOY) transcript to the chaincode-labs/chaincode-podcast directory.

### CODE REVIEW

**Comment by kouloumos** [comment]
Thank for your contribution @Numba1ne! This needs some work before is ready to merge. 

**Feedback on changes you did**
- Speakers names: Names are not accurate. You added the name "James O'Byrne" but if you look at the speakers' name in the metadata you will clearly see that the speaker's name is "James O'Beirne". Also, speaker detection might not be always accurate. For example, you correctly spotted in timestamp 00:13:01 that the same speaker is speaking - you should merge that in the same paragraph. There are a few more occasions of the same thing through the transcript.
- Chapter title disrupting the flow of a paragraph: You correctly catched some of those, but not all of them. 

**Feedback on editing**
- As you are listening to the source, feel free to make changes to the transcript that help with readability. Reviewers should strive for an "edited transcription" style, which can also be referred to as clean verbatim transcription. The goal of an edited transcription is to preserve the meaning of a text without paraphrasing. Stammering, filler words such as 'like' or 'you know', and unnecessary non-verbal communication can be omitted. **Strike a balance between completeness and readability**. We aim to provide a more detailed explanation of this review guideline on the website soon. Meanwhile, you can refer to https://github.com/bitcointranscripts/bitcointranscripts/issues/335 for additional insights.
- In general, after completing your edits, take a moment to read through the entire transcript. Consider its coherence and readability. Ask yourself: Does the transcript make logical sense? Is it easily understandable? This final review ensures the overall quality of the edited transcript.

This doesn't seem to need a lot of work. I believe that with another pass it will be ready to merge.

**Comment by Numba1ne** [comment]
Hello Andreas,

Thank you so much for the feedback.

I will work on it and resend the transcript today.

I hope I can get faster replies on my reviews.

One more thing, how much sats does one get paid per transcript?

With Regards,

Emmanuel Anthony.

**Comment by kouloumos** [comment]
> I hope I can get faster replies on my reviews. 

Our reviewing pipeline is relatively new, and we're continuously exploring ways to enhance productivity for all involved. We've been in the process of implementing some changes, causing delays in reviewing your submission. We were in the middle of changing a few things and that's why your submission had a delayed review. Our target is to have the first review within 24h. Rest assured, your future reviews will be expedited.

> One more thing, how much sats does one get paid per transcript? 

Sats are based on the length of the transcript. Can't say for sure how much this transcript is worth - the value should be available through the page.

**Comment by Numba1ne** [comment]
>> Sats are based on the length of the transcript. Can't say for sure how much this transcript is worth - the value should be available through the page.

> I could not find the worth, is there a way to check? it's 35 mins long - in audio length. Is there a minimum amount of sats?

**Comment by kouloumos** [comment]
> I could not find the worth, is there a way to check? it's 35 mins long - in audio length. Is there a minimum amount of sats?

It should be around 5000 sats

**Comment by kouloumos** [comment]
Hey @Numba1ne, are you still working on this?

**Comment by Numba1ne** [comment]
> Hey @Numba1ne, are you still working on this?

Yeah, it's just taking a while because I've been ill.

I'll complete it today.

**Comment by Numba1ne** [comment]
> Hey @Numba1ne, are you still working on this?

@kouloumos I'm done, I await your feedback

**Comment by kouloumos** [comment]
> @kouloumos I'm done, I await your feedback

I do not see any new changes, did you submit the updated transcript?
If you are editing through the website, you must re-submit.

**Comment by Numba1ne** [comment]
> > @kouloumos I'm done, I await your feedback
> 
> I do not see any new changes, did you submit the updated transcript? If you are editing through the website, you must re-submit.

I just tried re-submitting, I keep getting an error.

**Comment by kouloumos** [comment]
> I just tried re-submitting, I keep getting an error.

Can you send a screenshot of the error?

**Comment by Numba1ne** [comment]
> > I just tried re-submitting, I keep getting an error.
> 
> Can you send a screenshot of the error?

sinp
Here you go

**Comment by kouloumos** [comment]
> Here you go

Thanks! cc @Extheoisah

**Comment by Numba1ne** [comment]
> > Here you go
> 
> Thanks! cc @Extheoisah

Hello @kouloumos is there an update on this?

**Comment by kouloumos** [comment]
@Numba1ne please see #351, your issue is probably related, we are working on it.

As a workaround, you might consider editing the transcript using the [github.dev editor](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor) and manually committing your changes. If you choose this approach, please let us know if you encounter any challenges or issues along the way

**Pull request closed without merging**
