### PR TITLE
Add onion model deribit

### PR DESCRIPTION
**Pull request by jurraca**
A few questions here: 
is there a list of the full set of metadata options I could look at?
I think I'd rather it say "translated by: computer" or whatever and "edited by" for whoever formats and cleans up the generated translation. What do you think?

### CODE REVIEW

**Comment by adamjonas** [comment]
So the first commit is your standard awesome stuff.

The second commit causes some issues:

1. `Transcripción De:` no longer works...
Screen Shot 2022-03-23 at 6 25 49 PM

2. By making the headers h5s instead of h3s you lose the index, which I think is quite useful:
Screen Shot 2022-03-23 at 6 24 57 PM
vs.
Screen Shot 2022-03-23 at 6 25 23 PM

**Comment by adamjonas** [comment]
ping @jurraca

**Comment by jurraca** [comment]
yo @adamjonas so sorry for dropping this. Fixed the h5 down to a h4 (unless you want everything to be an h3?). 
Regarding the "Transcripcion de", I believe it pulls from the "Transcript By" field, but in this case since it's a published article I think it's correct to be empty.

**Review by kouloumos — COMMENTED** [review]
@jurraca unfortunately with h4 you still lose the index, you'll need to change that to h3 for the index to be displayed.

I understand that right now is difficult for contributors to render their transcripts and understand how they will be displayed in the website. Hopefully I'll introduce the needed changes for this to be easier in the future.

**Comment by jurraca** [comment]
thanks @kouloumos ! fixed. What do you want to do about the tags?

**Comment by kouloumos** [comment]
> thanks @kouloumos ! fixed. What do you want to do about the tags?

I don't have a strong opinion on that, but I supposed that if the translation is used by a native speaker, that's the one that we should use. In this case "cartera" not "wallet", "seguridad" not "security" but it will be the same in the case of "miniscript", "taproot" etc. 

Probably you and @BlueeeMoon have a better perspective on that. What do you think? 

In any case we should decide a stance to follow for all future translations.

**Comment by michaelfolkson** [comment]
I'd be a NACK for adding this to the repo. Up until now we've generally avoided adding articles to this repo in English or other languages. I'd be happy to make exceptions in extreme cases where the information is unique, historical and highly technical but I don't think this article (reading the English version) fits that criteria.

**Comment by jurraca** [comment]
That makes sense, and I agree that it would make sense to keep this repo for transcripts only. For context this came from translating the Chaincode seminar material.

**Comment by kouloumos** [comment]
I get Michael's view and after a bit of though I kind of agree with him. I understand the initial sentiment of adding the translations here but they would probably fit better in another medium (Medium or as supported translation on authors page).

Saying that, [a number of jurraca's articles translations have already been included](https://github.com/bitcointranscripts/bitcointranscripts/pulls?q=is%3Apr+is%3Aclosed+author%3Ajurraca), and although I think that this one is less technical than the rest, the question still remains, what are we gonna do with those? Do we remove them? Or keep them and also include this one as another one is not such a big deal? A few more pages is definitely not a big deal but it would be good to [set the bar for contributions](https://github.com/bitcointranscripts/bitcointranscripts/issues/8).

I would also consider having those on a separate branch as a point of reference until they find a better home.

**Comment by michaelfolkson** [comment]
@kouloumos: I don't think it is a big deal if we have a small number of stray articles in the misc directory that maybe shouldn't be there. Maybe keep the ones already merged, not merge this PR and hopefully going forward there is a bit more clarity for future PRs that are opened? We have to draw the line somewhere and it is inevitably going to be a bit hazy.

**Comment by kouloumos** [comment]
Sounds good and hopefully this kind of conversations add a bit of clarity for future contributors.

**Pull request closed without merging**
