### PR TITLE
Add simple-taproot-channels review to chaincode-labs/chaincode-podcast

### PR DESCRIPTION
**Pull request by TheFrayy**
This PR adds [simple-taproot-channels](https://podcasters.spotify.com/pod/show/chaincode/episodes/Elle-Mouton--Oliver-Gugger-and-Simple-Taproot-Channels---Episode-33-e2724sl) transcript review to the chaincode-labs/chaincode-podcast directory.

### CODE REVIEW

**Review by realdezzy — COMMENTED** [review]
Hey @TheFrayy ! Thank you for coming onboard and making a contribution to this project. Your efforts are sincerely appreciated.

Below are some of the errors found in your review, you are encouraged to check for similar errors across the transcript and make corrections.
-  Wrong host attribution(I have corrected them in [this commit](https://github.com/bitcointranscripts/bitcointranscripts/pull/487/commits/d5ecdd24f1dfc03fcbc19bd9f73c9895d918d91b)).

 Hosts are not included in the speakers metadata but are attributed when they make contributions to the discussion
- Make an effort to research names of hosts and speakers to make sure they are real
- When the speaker name cannot be inferred, use the "speaker + number" format to name them.

- line 31 Your use of single quotes is wrong, my guess is that you are mistaking them for  backticks.
Please bear in mind that not all abbreviations require backticks, as we use backticks strictly  for opcodes, equations and functions  e.g `getblocktemplate`

-  Change the occurrences of music to either musig or musig2 depending on what the speaker says
- There seem to be lots of AI errors, please go through the material again and try to improve your work

Since you are a new reviewer, I invite you to join our [Bitcoin Dev Project discord](https://discord.gg/MhK7C79RQS). This platform will allow you to ask questions, connect with other reviewers, get notified about new transcripts available for review, and explore ongoing developments in the Bitcoin Dev Project.

**Comment by TheFrayy** [comment]
Ah, perfect.

I was looking for clarification on that but didn't see anything in the
Docs. Good to know, thanks


*Frazer Sloan, MBA | Strategy Officer*
Kaizen Group
Mobile: 403-815-4418
***@***.*** | kaizenauto.com

**Comment by kouloumos** [comment]
I've left some comments inline for reference. As you can see, I addressed these issues in my [fixup commit](https://github.com/bitcointranscripts/bitcointranscripts/pull/487/commits/289fe89fd753514e2735a71e23029226567d42a8). Please review our evaluation comments and feedback on this submission before starting another one.

Thank you for your contribution, @TheFrayy. We look forward to seeing more of your reviews soon! 🚀

**Comment by TheFrayy** [comment]
For sure.

Hmm, regarding more technical terms, any recommended resources for
clarifying? For example, I genuinely didn't know if it should be on-chain
or onchain.

Thx



*Frazer Sloan, MBA | Strategy Officer*
Kaizen Group
Mobile: 403-815-4418
***@***.*** | kaizenauto.com

**Comment by kouloumos** [comment]
> Hmm, regarding more technical terms, any recommended resources for
clarifying? For example, I genuinely didn't know if it should be on-chain
or onchain.

We plan to create a list of conventions for bitcoin technical terms soon.
To give you a bit more insight, we are planning to extend [this document](https://github.com/bitcoinops/bitcoinops.github.io/blob/master/STYLE.md) for our needs, so that's where the "onchain" vs "on-chain" came from. No need to care about that for now.

**Pull request merged**
