### PR TITLE
Add libsec-panel to bitcoin-review-podcast

### PR DESCRIPTION
**Pull request by fjahr**
This PR adds [Libsec Panel](https://www.youtube.com/watch?v=8Z79CeBw3Nc) transcript to the bitcoin-review-podcast directory.

### CODE REVIEW

**Comment by fjahr** [comment]
I am seeing now that others have kept the timestamps in the transcript. I removed them after looking at an older podcast transcript as an example: https://btctranscripts.com/what-bitcoin-did-podcast/2019-05-14-adam-back-bryan-bishop-block-reorgs/ IMO removing them is better because it makes reading much easier.

**Comment by kouloumos** [comment]
> I am seeing now that others have kept the timestamps in the transcript. I removed them after looking at an older podcast transcript as an example: https://btctranscripts.com/what-bitcoin-did-podcast/2019-05-14-adam-back-bryan-bishop-block-reorgs/ IMO removing them is better because it makes reading much easier.

Before AI transcription, we didn't use timestamps. Because we now get them "for free" through diarization, we're exploring how to store and present them, considering their potential as metadata for future use. 
Regarding the reading experience, an idea is to have a regex that will remove them for the users of btctranscripts.

**Comment by kouloumos** [comment]
Thank you for the contribution @fjahr!

I've pushed some fixups, just a note for future reviews: Try to use an ["edited transcription" style](https://github.com/bitcointranscripts/bitcointranscripts#transcription-style), which can also be referred to as clean verbatim transcription. The goal of an edited transcription is to preserve the meaning of a text without paraphrasing. Stammering, filler words such as 'like' or 'you know', and unnecessary non-verbal communication can be omitted. Strike a balance between completeness and readability.

Some examples of the fixups that I did following this transcription style:
- filler words: "I think both because, ~you know,~ in a way or another, ~I mean, like, you know,~ the code is what makes Bitcoin, ~you know,~ happen."
  - becomes "I think both because, in a way or another, the code is what makes Bitcoin, happen"
- stammering&filler words: "There's a lot of dabs out there that ~like, you know, they're,~ they are working more on the business logic level." 
  - becomes: "There's a lot of dabs out there that they are working more on the business logic level"
- rephrasing: "There's the LightningDevKit as well that ~is trying to do,~ has a very similar goal for Lightning, have composable tools that ~let make you use,~ allow you to ~use,~ implement the Lightning protocol in your stack, giving a simpler experience for your users because ~it's not,~ you're not having to run some extra node. It's like integrated into the app.
  - becomes: "There's the LightningDevKit as well that has a very similar goal for Lightning, have composable tools that allow you to implement the Lightning protocol in your stack, giving a simpler experience for your users because you're not having to run some extra node, it's like integrated into the app."
  
 Thanks again!🚀

**Comment by fjahr** [comment]
@kouloumos Alright, that makes sense, thanks for the heads-up!

Some feedback from my side on the estimate: It took 2-3x the estimated time for me to make this review as is. I am not sure how you make the estimates (I guess based on word count?) but in this case, there were a lot of participants who talked over each other and I needed to listen to the original to make out who said what many times and the original podcast was almost 2h with the estimate being 1h. Also, the tools discussed (libsecp, zkp, valgrind etc.) were all butchered in many different ways by the AI so search and replace didn't help. The AI also struggled with non-native English, for example when a German said "math" it came out as "marv". Maybe you can factor this in somehow to improve future estimates. I am pretty sure a conversational podcast with multiple participants always requires more editing than a 1-on-1 interview or a straightforward presentation.

**Comment by kouloumos** [comment]
Appreciate the feedback @fjahr! Feedback is important at this stage of the project as we are still figuring things out towards making this process as productive as possible for everybody involved. 

You are right, the current estimate is based on word count, but it seems that we need to rethink that. The initial estimate should probably be closer to the duration of the audio with extra time added for multispeaker and other variables.

Also, did you use the in-app editor for your review?

**Comment by fjahr** [comment]
I only explored the online editor for a few minutes but saw some lagging so I copied the content and switched to my normal editor. I am used to my shortcuts there and also I know markdown so this way it was very close to my usual workflow for some static site generator websites I edit sometimes.

**Pull request merged**
