### PR TITLE
add github action to tweet for new transcripts

### PR DESCRIPTION
**Pull request by kouloumos**
### Motivation

I believe that there are people out there that would be interested for this project but are not aware of it yet. I think that leveraging the inactive twitter account [@bitcoinwritings](https://twitter.com/bitcoinwritings) to tweet when a new transcript is added is a good hustle-free way to increase awareness and possibly attract more contributors.

### Overview

The idea behind this PR is that every transcript addition that is pushed on this repository (content's repository) will trigger a tweet, currently in the following format: 
demo-tweet
(The displayed account is what I am using for the demos of this implementation)

The current implementation tweets only for additions of single files, can separate between languages and is using the file path as the url of the transcript (which is how Hugo builds the new site).

You can see demos in my [demo-branch](https://github.com/kouloumos/bitcointranscripts/tree/twitter-bot-demo) for
- English: [github action](https://github.com/kouloumos/bitcointranscripts/runs/6971683845?check_suite_focus=true), [tweet ](https://twitter.com/bitcoinrugs/status/1538937501179645959)
- Spanish: [github action](https://github.com/kouloumos/bitcointranscripts/runs/6971733179?check_suite_focus=true), [tweet](https://twitter.com/bitcoinrugs/status/1538938549667512321)
- Portuguese: [github action](https://github.com/kouloumos/bitcointranscripts/runs/6971718458?check_suite_focus=true), [tweet](https://twitter.com/bitcoinrugs/status/1538938236055134208)

### Prerequisites

The [GitHub action](https://github.com/Eomm/why-don-t-you-tweet) that is used for this functionality requires 4 secrets to be added to the repository. This is relatively simple and the README of the linked GitHub action explains the details. The only part that is missing is how to change app permissions, which [is explained here](https://twittercommunity.com/t/changing-app-permissions-missing-in-ui/163708/9). (be aware that changing the app permissions results to new keys & secrets)

### CODE REVIEW

**Comment by michaelfolkson** [comment]
I transferred the btctranscripts Twitter account to @Caralie. She might be willing to transfer it over to you @kouloumos

**Comment by adamjonas** [comment]
I've added those secrets for bitcoinwritings

**Comment by kouloumos** [comment]
Merged in anticipation of testing with https://github.com/bitcointranscripts/bitcointranscripts/pull/169, but I forgot that this action tweets only on single file changes, so because that PR also added  an `_index.es.md` file, it did not work. I'll wait for another transcript to confirm that this works as it is and I'll probably make another change to also take into consideration index files.

**Comment by adamjonas** [comment]
Adding a index is a pretty standard thing. I'd say it's worth updating if this is something we want for the long term.

**Comment by Caralie** [comment]
> > I transferred the btctranscripts Twitter account to @Caralie. She might be willing to transfer it over to you @kouloumos
> 
> Thanks for the input. Although my twitter-bot approach doesn't need continues access, it would definitely make things easier. However, if there is consensus for this, we will still need someone with sufficient access (possibly @adamjonas) to add the secrets to the repository.

Sorry for my delay here! Just gave @kouloumos access to the btctranscripts account

**Pull request merged**
