### PR TITLE
Add demystifying-and-understanding-bitcoin-core-development to bitcoin-review-podcast

### PR DESCRIPTION
**Pull request by realdezzy**
This PR adds [Demystifying and Understanding Bitcoin Core Development](https://www.youtube.com/watch?v=uOhkN4nefpI) transcript to the bitcoin-review-podcast directory.

### CODE REVIEW

**Comment by kouloumos** [comment]
Hey @realdezzy! Thank you for taking this. Even though it's not heavily technical transcript I consider it very insightful.

Your edits are well done, but I noticed the removal of timestamps and changes to the original format. This wasn't done in your initial submission in #361. Restoring the original timestamps isn't straightforward right now, as it might erase your current edits. One way to tackle this could be copying your current work into a new file, then restoring the original and manually merging the two versions. This approach could streamline the process.

**Comment by realdezzy** [comment]
@kouloumos how do I get the timestamps in?
The transcript from the AI did not come with timestamps

**Comment by kouloumos** [comment]
> @kouloumos how do I get the timestamps in? The transcript from the AI did not come with timestamps

Oh, I am not sure what might happened and timestamps were not there when you originally started editing the transcript.
To assist, I've included the original transcript in [this gist](https://gist.github.com/kouloumos/68363fb17ab2c642f074864db7b60ade) for your convenience.

**Comment by kouloumos** [comment]
Hey @realdezzy, thank you for taking the time to restore the timestamps and original formatting and apologies for the delay to get back to this. You did an amazing job with catching AI's transcription errors, but it seems this still needs a bit more work before it's ready to merge.

As we continuously strive to enhance productivity, recent reviews have highlighted a need for clearer communication of our expectations to reviewers. I anticipate that we'll soon provide more comprehensive Review Guidelines to clarify expectations. In the meantime, please read the Review Guidelines in https://github.com/bitcointranscripts/bitcointranscripts/issues/348, and you can see an examples of 'right editing' in https://github.com/bitcointranscripts/bitcointranscripts/issues/335.

Incorporating these insights will significantly refine the transcript effectively. Feel free to reach out if you have any questions.
This feedback also applies to your other pending reviews: #363 & #364.

**Comment by realdezzy** [comment]
@kouloumos I am unsure of what to do next, can you point me in the right direction?

**Comment by kouloumos** [comment]
Hey @realdezzy, I've been doing some thinking about how we approach our review process. First up, I really need to apologize. Looking back, I realize I might have set the bar a bit too high in terms of the level of polish I was expecting on the transcripts. It's important for me to acknowledge that this project, like any work in progress, is about finding the right balance that makes this process both productive and enjoyable for everyone involved.

Reflecting on your recent work and the feedback from others, I see now that my focus on formatting and perfection may have overshadowed the truly crucial part of your contribution – correcting AI transcription errors in a 2-hour transcript. Your dedication to making the transcript readable and accurate is far more valuable than the strict formatting standards I was initially aiming for. You did an amazing job, and I want to make sure you know that.

So, I'm adjusting my lens a bit. Yes, striving for perfection is good, but not at the expense of our well-being or losing sight of what's really important – making the content accessible and correct. Your work has highlighted the need for a shift in priorities, with a greater emphasis on fixing AI errors and ensuring the transcript's accuracy above all.

I genuinely appreciate the effort you've put in and the quality of your work. I hope my previous guidance didn't add unnecessary stress. Moving forward, I'm all about supporting you and all our reviewers in making contributions that you can be proud of, without the pressure of unattainable perfection.

I've pushed [a couple last fixups](https://github.com/bitcointranscripts/bitcointranscripts/pull/362/commits/a5f61bd51c2a968715e61aaad2b0cbb950476b96) and this is now ready to merge!

Let's keep the focus on learning, improving, and diving deeper into the world of Bitcoin together. And remember, our Discord server is always there if you have questions, need support, or just want to chat with fellow contributors.

Thanks for your understanding, your incredible work, and for being part of this effort.

**Comment by realdezzy** [comment]
Thanks for the kind words @kouloumos. It's not wrong to pursue perfection since this work will most likely outlive us.
Also, I noticed I did not get SATS in my profile, it also had the expired & live status.
How can I correct that?

**Comment by kouloumos** [comment]
> Also, I noticed I did not get SATS in my profile, it also had the expired & live status. How can I correct that?

Do you use Discord? I already sent you [an invite](https://discord.gg/76wCxgeyvM) in a previous message, we have a dedicate channel there for questions and issues, it would make troubleshooting easier.

**Comment by realdezzy** [comment]
> > Also, I noticed I did not get SATS in my profile, it also had the expired & live status. How can I correct that?
> 
> Do you use Discord? I already sent you [an invite](https://discord.gg/76wCxgeyvM) in a previous message, we have a dedicate channel there for questions and issues, it would make troubleshooting easier.

Thanks for the invite, I just joined

**Pull request merged**
