### PR TITLE
Add hd-wallets-mnemonic-codes-and-seedqr to bitcoin-magazine/bitcoin-explained

### PR DESCRIPTION
**Pull request by QureshiFaisal**
This PR adds [HD Wallets, Mnemonic codes and SeedQR](https://www.youtube.com/watch?v=s8dCyjpfS5E) transcript to the bitcoin-magazine/bitcoin-explained directory.

### CODE REVIEW

**Comment by kouloumos** [comment]
Thank you for your contribution @QureshiFaisal! 

It's important to keep the original format of the transcription alongside the timestamps. Retaining timestamps and preserving the original formatting (speaker name \n text \n) is crucial. Consistency in transcript structure will be pivotal if there's a future decision to programmatically modify the format. It also helps when reviewing the submission!

As soon as you update the transcript to the original format I will be able to continue with the review. Thank you!

**Comment by QureshiFaisal** [comment]
Added timestamps, and implemented the suggested changes.

**Comment by kouloumos** [comment]
> Added timestamps, and implemented the suggested changes.

Hey @QureshiFaisal did you update the transcript thought the website?

**Comment by QureshiFaisal** [comment]
> > Added timestamps, and implemented the suggested changes.
> 
> Hey @QureshiFaisal did you update the transcript thought the website?

Yes, I updated it through the website.

**Comment by kouloumos** [comment]
Thank you @QureshiFaisal! I've pushed some fixups and is now ready to merge! I've wrote some feedback notes that might be helpful for your future reviews.

**Feedback for you**
- Transcript structure: You added the timestamps, but you didn't add the empty line after each timestamp. If multispeaker, keep the format:
  ```
  <Speaker name>: XX:XX:XX
  (empty line)
  Text
  ```
- Transcription style:  **Strike a balance between completeness and readability**
  - Consider removing non-essential lines, e.g  "Well...", "Hmmm" or "Yeah." to enhance clarity and flow.
  - Consider removing mid-phrase rephrasings/corrections, e.g "**But when you use it, it's actually** ~not using the words. Sorry, it's~ **not going back to the numbers**.", "**Because** ~six,~ **if you have a 12 word seed and you cut it in two, that's six words each.**", "~And~ **A QR code** ~is every,~ **if you read it from left to right, basically it's either black or it's white**."  or filler words: "**If they go to your home they can,** ~you know,~ **that's that's a trade-off.**" to enhance clarity and flow .
  - In general, reviewers should strive for an "edited transcription" style, which can also be referred to as clean verbatim transcription. The goal of an edited transcription is to preserve the meaning of a text without paraphrasing. Stammering, filler words such as 'like' or 'you know', and unnecessary non-verbal communication can be omitted. Strike a balance between completeness and readability.
- If the transcript contains ads, remove them.

**Feedback for us**
[We'd love to hear your feedback](https://cryptpad.fr/form/#/2/form/view/3P2CsohsHOkcH7C+WdtX0-tvqjBHqXnAmz5D9yx0e04/) for this project and your experience as a reviewer (anonymously) as we are trying to improve and make the experience better for all.

**Pull request merged**
