### PR TITLE
Add silent-payments review to bitcoin-design/learning-bitcoin-and-design

### PR DESCRIPTION
**Pull request by nymius**
This PR adds [silent-payments](https://www.youtube.com/watch?v=Cqmk2cZ2IjM) transcript review to the bitcoin-design/learning-bitcoin-and-design directory.

### CODE REVIEW

**Comment by kouloumos** [comment]
Hey @nymius! This is a great review, thank you for your contribution! You did an excellent job catching AI transcription mistakes and improving readability. I only had to make some [minor adjustments](https://github.com/bitcointranscripts/bitcointranscripts/pull/475/commits/b8d7b86bb6d2466f6712dc4272d19127323394eb).

Regarding the metadata, as shown in [this commit](https://github.com/bitcointranscripts/bitcointranscripts/pull/475/commits/cdb75ef890e62d70e565a047eb800d819a60163e)::
1) I removed some of the extra tags you added. We want to make it easier for reviewers to understand our tagging conventions. For example, the `silent-payments` tag includes `privacy`, `privacy-enhancements`, and `transaction-origin-privacy`, so those additional tags aren't necessary.
2) I added the rest of the speakers you attributed in the speakers list and adjusted the in-transcript attributions to match the actual speaker names. 

###  AI experiments

In my last two commits, you can see some of the AI experiments we're running. The continuous advancement of AI makes experimentation essential as we strive to enhance our work and increase the productivity and efficiency of our reviewers. Currently, we're experimenting with [AI-generated summaries](https://github.com/bitcointranscripts/bitcointranscripts/pull/475/commits/20addf899a63aec83ab085627e2ee664988b7b3c) for the transcripts.

Additionally, for the first time in your review, I used AI (specifically, OpenAI's latest gpt-4o model) to edit the transcript based on our reviewing guidelines. The [related commit](https://github.com/bitcointranscripts/bitcointranscripts/pull/475/commits/e012f370689d30f921edf2ccea6a12d1a5e7f61e) shows several changes the AI made to remove distractions such as false starts, filler words, stammers, and occasional structural adjustments to improve readability. If we proceed with this approach, AI editing would occur before you claim the transcript, ensuring that you review a more readable version from the start.

This phase is still experimental, and I would greatly appreciate your feedback. Here are a few observations I have about the AI changes:
- One of our guidelines for reviewers is to avoid paraphrasing. Despite my efforts to enforce this in my prompt, the AI made some minor paraphrasing edits. I'm uncertain if this is a significant issue.
- Occasionally, the AI mistakenly deletes words or larger text segments, meaning we can't fully trust the output without review. Therefore, we might ask reviewers to evaluate the AI's edits, effectively turning reviewers into evaluators for the "AI editor."

I have a couple of questions for you:
1. What is your opinion on the [changes made by the AI](https://github.com/bitcointranscripts/bitcointranscripts/pull/475/commits/e012f370689d30f921edf2ccea6a12d1a5e7f61e)?
2. Would you find value in this approach if we also asked you to review the changes made by the "AI editor"?

**Comment by nymius** [comment]
Hi @kouloumos, thanks for the review!
In relation to the second point about the transcript metadata, I think that if we add the other speakers, to keep the consistency of the guidelines, we should add Adam and Mark [here](https://github.com/bitcointranscripts/bitcointranscripts/pull/474) too.

Regarding the summary, I couldn't do better than the AI, the paragraph is clear, concise, summarized the majority of points and the tone is very "academic".

To answer directly your later questions:
1. I think the AI intervention really improves the readability of the document, beside the paraphrasing.
In parts where I already thought it would be good to remove some words, but didn't do it afraid of doing too much, it did it with great criteria.
In this transcript there were a lot of "impersonations", that the AI catched really well, surrounding the expressions with double quotes every time.
The paragraph separation is good. I didn't dig too much in those aspects of the transcription, before, trying (again) to not do too much, but I agree the AI changes did the read easier, joining related sentences together in the same paragraph or breaking them depending on the context.
I'm also surprised how well the chapter names where chosen, and how the talk flow was split correctly by them. The result is really useful when you are looking at particular aspects of a topic, because it improves discoverability and linkability.

2. Yes. I think we should consider the differences between listening and reading. Phrases, repetitions, stammers and other things are filtered during listening, but while reading they are hard to avoid, and you could be left wondering why you shouldn't go directly to the audio version instead. I think transcripts should stand as end resources themselves, without needing second thoughts of the underlying sources.
In general, I would say that using an AI editor as the first transcriptor is going to improve the process. Fast and probably wrongly explained, is a convoluted way to use the median of some Gauss bell with all the ways of transcription and formal writing "we" had. Obviously, we still need the human in the middle to curate the output, but I cannot see the negative aspect of it yet.

**Comment by kouloumos** [comment]
> In relation to the second point about the transcript metadata, I think that if we add the other speakers, to keep the consistency of the guidelines, we should add Adam and Mark https://github.com/bitcointranscripts/bitcointranscripts/pull/474 too.

Good point! Although I'm not sure that the Bitcoin Design calls have a specific host in the same way that a podcast has. Other than Josie, the rest of the participants are all members of the Design community. I'm not sure how we should handle scenarios like this. Good things is that we can always come back and make global adjustments.

>  In general, I would say that using an AI editor as the first transcriptor is going to improve the process. 

Thank you for your feedback. I thought a bit more on this idea, and I believe it will be more productive to do the AI editing after the initial review. So the reviewers focuses only on AI transcription mistakes and after they submit, the AI editor focuses on readability and we ask from the reviewer to review those edits.

**@nymius would you like to participate in the first experiment of reviewing the AI edits?**

We currently lack a dedicated interface for this, so we'll use GitHub to inspect the differences between the versions. The easiest and quickest way to review the AI edits is by observing [this commit](https://github.com/bitcointranscripts/bitcointranscripts/pull/475/commits/e012f370689d30f921edf2ccea6a12d1a5e7f61e). However, GitHub's display of changes can make it difficult to understand the specific modifications made to each line. To address this, you'll need to use github.dev. I've recorded a quick walkthrough on how to do this: [Video Walkthrough](https://www.youtube.com/watch?v=IRBCwrjKDjA).

**Instructions alongside the video:**
1. While on GitHub.com, simply press the "." key on your keyboard to switch to github.dev, or change the URL to "github.dev".
2. In the left sidebar, click on the last option labeled "GitHub Pull Request". There, you can see all the commits of this Pull Request.
3. To review the specific changes related to the AI edits, click on the last commit and then on the file name.

In the split view, you should be able to scroll and see the AI changes side by side.

**Tip**: If words are not wrapping, it makes it harder to review the changes. Use the shortcut "Alt+Z" to toggle word wrap.

no words wrap
_No words wrap_
words wrap
_Words wrap_

4. While reviewing, if you see something that needs to change, you can make the edit directly there. Save your changes with Ctrl+S or by using the menu:
image

5. After finishing the review, you need to commit your changes. Click on the third option in the left sidebar called "Source Control". There, you can see your changes. First, "Stage" them, then write a commit message, and click the "Commit & Push" button.

I understand this is a more involved process, which is why we're building a review platform to simplify contributions and abstract GitHub complexities. I hope the recording and instructions make it easier for you. If you have any questions, feel free to reach out directly on Discord.

**Comment by nymius** [comment]
> Good point! Although I'm not sure that the Bitcoin Design calls have a specific host in the same way that a podcast has. Other than Josie, the rest of the participants are all members of the Design community. I'm not sure how we should handle scenarios like this. Good things is that we can always come back and make global adjustments.

Well, there we have another thing to differentiate in a possible FAQ: What kind of content are you transcribing? Podcast? Socratic Seminar? Talk? How you should transcript on each case? How you should tag the different speakers?

> Thank you for your feedback. I thought a bit more on this idea, and I believe it will be more productive to do the AI editing after the initial review. So the reviewers focuses only on AI transcription mistakes and after they submit, the AI editor focuses on readability and we ask from the reviewer to review those edits.

Looks good for me!

> **@nymius would you like to participate in the first experiment of reviewing the AI edits?**

I would like to say yes, but I've tried to follow your instructions and the github live coding platform doesn't allow me to make use of it without letting it have access to data I don't want to breach. May sound silly but each step back is something you won't get back later, so I cannot contribute using the interface you are talking about. I know you are trying to use these features to make it more accessible to not tech-savvy transcribers, but as I said, I don't want to make steps back.

If it's okay for you, I can do reviews using the old Pull Request flow with git.

**Comment by kouloumos** [comment]
> If it's okay for you, I can do reviews using the old Pull Request flow with git.

You can do it however you want, as long as it's productive for you.

Once you've completed the review, I would like to know:
1. How much time does it take you to do that final review?
2. Is it fun? Did you get something out of it?
3. Comments about the edits of the AI editor.

Thank you!

**Comment by nymius** [comment]
Hey! I've finished the review. I think this one is ready.

Answering your questions:
1. An hour and a half for the final review. Considering I was also listening the audio at speed (x1.75) while I was reading the changes, with a few backs and forth of the track.
2. The first round of listening and transcription was very instructive and funny. It seems the topic gained a lot of traction in the last months so the transcription was just in time. The other rounds became more of a routine, with the lost of fun you have when you lose the effect of surprise, but also made me grasp more details or lines of further research with the repetition.
3. I didn't have to correct any of the last AI changes. I think all of them were well applied and improved the reading experience of the transcription. It doesn't feel as natural as listening to the conversation, but for me it is better from a reader's point of view.

**Comment by kouloumos** [comment]
Thank you for putting this extra effort @nymius!

> An hour and a half for the final review. Considering I was also listening the audio at speed (x1.75) while I was reading the changes, with a few backs and forth of the track.

I wasn't expecting that re-listening to the audio was necessary for this final review. You (the reviewer) have already listened to the audio during the first phase of the review therefore you know that (after your edits) the audio matches the final text.

For this second phase (after the AI edits) just looking at / reading through the split-screen differences between the two versions should be enough and much quicker than re-listening. What do you think?

**Comment by nymius** [comment]
Totally! I wanted to check my final version (beyond the changes made by AI) were correct too, as in my other review you discovered an error after I marked it as final.

Will stick to the workflow more tightly for my next review, so you can have real expectations about time consumed.

**Comment by kouloumos** [comment]
Awesome, I'll merge this one, looking forward to seeing more of your reviews in the future! :rocket:

**Pull request merged**
