### PR TITLE
Add Greg on bech32 design

### PR DESCRIPTION
**Pull request by michaelfolkson**

### CODE REVIEW

**Comment by kouloumos** [comment]
Is this just a copy of the referenced bitcointalk post? Do we consider this a transcript? 

We also have the example of https://github.com/bitcointranscripts/bitcointranscripts/pull/126 for which I also suggested that we could introduce an `article` category. Maybe a category distinction here would also make sense?

**Comment by michaelfolkson** [comment]
@kouloumos: [This](https://github.com/bitcointranscripts/bitcointranscripts/issues/8#issuecomment-815054718) is the approach I personally take.

> I feel that an interesting explanatory Reddit post or Bitcointalk post on a technical topic can squeeze into the transcripts definition (others may disagree) as a standalone transcript even though it was never delivered verbally. Especially if you would seek to link to it from another transcript or it would likely get lost and forgotten about otherwise. Just be clear where the "transcript" has come from.

I don't think we want to collect every article ever written on Bitcoin technical topics in this repository but Greg especially has a number of educational comments scattered around Reddit and Bitcointalk that aren't indexed and risk getting lost otherwise.

**Comment by kouloumos** [comment]
I agree with that approach. 

I also saw that this is not the first bitcointalk/reddit post to be included. Do you think that having `bitcointalk`,`reddit` categories for this kind of content would make sense? Mostly for better indexing.

**Comment by kouloumos** [comment]
Sounds good!

**Pull request merged**
