### PR TITLE
Add bitcoin-explained-episode-81:-bitcoin-core-25.0 to bitcoin-magazine/bitcoin-explained

### PR DESCRIPTION
**Pull request by edilmedeiros**
This PR adds [ Bitcoin Explained - Episode 81: Bitcoin Core 25.0 ](https://www.youtube.com/watch?v=TN2P9xwd6ZU) transcript to the bitcoin-magazine/bitcoin-explained directory.

### CODE REVIEW

**Comment by edilmedeiros** [comment]
I see now that I should have kept the timestamps. 
Where may I find the original AI transcript to make the adjustment easier?

**Comment by kouloumos** [comment]
Hey @edilmedeiros, inside the editor you can always click the "Restore Original" button and get back to the original format, but doing that isn't straightforward right now, as it might erase your current edits. One way to tackle this could be copying your current work into a new file, then restoring the original and manually merging the two versions.
To assist, I've included the original transcript in [this gist](https://gist.github.com/kouloumos/4a6fa7cad54b58783cd3161f68361eba) for your convenience.

Also, there is no need to include extra metadata at the beginning of your transcript - we are doing that automatically.

**Comment by edilmedeiros** [comment]
This should be good now, @kouloumos.

**Comment by kouloumos** [comment]
Thank you for your contribution @edilmedeiros ! Your work on catching AI's transcription errors, eliminating filler words and incorporating punctuation marks has significantly elevated the readability of the transcript. The addition of chapters as well as extra tags is fully appreciated. I've pushed some minor fixups that you can see [here](https://github.com/bitcointranscripts/bitcointranscripts/pull/375/commits/84b28cd338e623a6b58fb8e4536d73c6ea40b15f).

**Feedback for future work**:
- We don't need the ads, you can remove them when they exist.
- Feel free to remove mid-sentence rephrasings and non-essential lines; examples are highlighted in my fixup commit.

Thank you for the feedback that you already gave us regarding your experience as a reviewer.
We've recently set up a Discord server where you can join fellow contributors, ask questions, provide feedback, and receive real-time notifications for new transcripts available for review. You can join by clicking [here](https://discord.gg/76wCxgeyvM).

We hope that you learn something out of this and looking forward to more such great reviews!

**Pull request merged**
