### PR TITLE
Add let's-talk-about-dual-funding:-protocol-overview to bitcoinplusplus

### PR DESCRIPTION
**Pull request by saltykate**
This PR adds [Let's Talk About Dual Funding: Protocol Overview](https://www.youtube.com/watch?v=OFMU1xV5uQk) transcript to the bitcoinplusplus directory.

### CODE REVIEW

**Comment by kouloumos** [comment]
Thank you for your contribution @saltykate! It's great that you put the extra effort to add chapters and links! It really helps with readability!

This looks like an interesting transcript, but as it is I'm having hard time reading it. Reviewers should strive for an "edited transcription" style, which can also be referred to as clean verbatim transcription.  The goal of an edited transcription is to preserve the meaning of a text without paraphrasing. Stammering, filler words such as 'like' or 'you know', and unnecessary non-verbal communication can be omitted. Not everything has to be perfect, just try to **Strike a balance between completeness and readability**, and there are plenty of phrases that can be deleted/modified towards that goal. For example:
- "~Object? What did you say? Shut up. I didn't check. I thought it was a normal code. Object-oriented programming Never made it to Bitcoin? No? OK. All right.~" (unnecessary)
- "~Can you guys read that? That's okay. Great, okay, good. Great, perfect. Wow, that's good. That's good. OK. All right, great. All right, so lightning channel. All right, so the question is then, so OK, then~ **the process of opening a lightning channel,** ~of opening a lightning channel,~ **how do we make that work?**"
- "Does anyone remember what the downsides were? ~Drawbacks All the money is out on the other one Yeah~ All the money is on one side." (mid-sentence rephrasing)
- "~And so then now you also need to send,~ **you need to send also at the end**. ~So after you constructed the transaction,~ **so you construct the transaction** ~, right, together.~ **And then you exchange signatures that let you** ~spend from that transaction,~ **spend from that transaction, right?**"

Also, some other feeedback:
- It was a good idea to add scripts and code in their own lines. It's suggested to add those in code blocks. So for example:
  ```
  OP_2 <pubkey1> <pubkey2> OP_2 OP_CHECKMULTISIG
  ```
- Try to capitalize the chapters, e.g "Dealing with Liquidity" instead of "dealing with liquidity"

Let's take this to the finish line. Thank you again for your effort!

**Comment by saltykate** [comment]
Hi Andreas,

Thank you for feedback, this is very helpful for me to do better. It was a bit ambitious for me to try - I understand and did not know that it ok to amend the filler (I will chop and slash as needed:) - I will get back to it and resubmit.

Can you please clarify:

- It was a good idea to add scripts and code in their own lines. It's suggested to add those in code blocks. So for example:

OP_2 <pubkey1> <pubkey2> OP_2 OP_CHECKMULTISIG

When you say “add those in code blocks” is this not what I did?

Thank you.
Kate

**Comment by kouloumos** [comment]
> When you say “add those in code blocks” is this not what I did? Thank you. Kate

You have the scripts in a separate line, but in markdown to denote a word or phrase [as code](https://www.markdownguide.org/basic-syntax/#code), you can enclose it in backticks (`). 

So "OP_2 <pubkey1> <pubkey2> OP_2 OP_CHECKMULTISIG" enclosed in backticks, becomes "`OP_2 <pubkey1> <pubkey2> OP_2 OP_CHECKMULTISIG`" which can also be written in-line with the rest of the content.

When you have multiple lines of code you can enclose it in triplebackitics (\```) which creates a new text block like this: 

```
OP_2 <pubkey1> <pubkey2> OP_2 OP_CHECKMULTISIG
```

**Comment by kouloumos** [comment]
Hey @saltykate , are you still working on this?

**Comment by saltykate** [comment]
No, not had time to revisit, this is as far as I will take it

**Comment by kouloumos** [comment]
> No, not had time to revisit, this is as far as I will take it

Hey @saltykate,  we continuously strive to enhance productivity for everybody, so I would like to hear more regarding you experience. I believe that among the roughly 40 transcript reviews that we had since launch, yours has involved the most back-and-forth communication and edits. This suggests that perhaps we might have unintentionally exceeded the anticipated time you intended to invest in this process.

I'm genuinely interested in your perspective: do you feel that our requests might have been too demanding? We're actively addressing this by working on clearer communication of our expectations to reviewers right from the get-go. Your insights could immensely help us refine and streamline our review process moving forward.

**Comment by kouloumos** [comment]
Hey @saltykate! Given that it was one of the initial reviews on our platform, we were still in the process of defining our expectations and processes for reviews. This, coupled with the complexity of the transcript you handled, made your task particularly challenging.

I have since [made the necessary adjustments to complete the review.](https://github.com/bitcointranscripts/bitcointranscripts/pull/325/commits/d6be5fd337c25f03fde0f0eefa860fe0f55d5ddd) I want to assure you that your initial work was invaluable, and it played a crucial role in helping us evolve our approach. We have learned a great deal since then, and have made significant improvements to the Bitcoin Transcripts project, aiming to streamline our procedures and better support our reviewers.

With this progress, we are excited about the future of our platform and sincerely hope to see more of your reviews. I also would like to invite you to join our [Bitcoin Dev Project Discord](https://discord.gg/76wCxgeyvM), where you can connect with fellow reviewers, ask questions, stay updated on new transcripts available for review, and engage with ongoing developments in the Bitcoin Dev Project.

Thank you once again for your contributions. Your involvement is crucial to our continuous improvement and success. We look forward to your continued participation and are eager to support you in any way we can!

**Pull request merged**
