### PR TITLE
add coredev april 2023

### PR DESCRIPTION
**Pull request by adamjonas**

### CODE REVIEW

**Comment by josibake** [comment]
FYI: I'm not seeing these on https://btctranscripts.com/bitcoin-core-dev-tech/ , but maybe I'm looking in the wrong place?

**Comment by adamjonas** [comment]
Fixed

**Comment by josibake** [comment]
follow-up: is there a reason we don't have all of the "Core Dev Tech" notes bucketed by date? We do for the 2015 meetup but not the others. If there are no objections, I'll open a PR to bucket the others. Having them bucketed would make it much easier to reference "here is what was covered at the last core dev" , etc

**Comment by kouloumos** [comment]
> follow-up: is there a reason we don't have all of the "Core Dev Tech" notes bucketed by date? We do for the 2015 meetup but not the others. If there are no objections, I'll open a PR to bucket the others. Having them bucketed would make it much easier to reference "here is what was covered at the last core dev" , etc

It seems reasonable. You'll just need to account for the url change in order to avoid broken links. To do that you can create aliases, see https://github.com/bitcointranscripts/bitcointranscripts/pull/219

**Comment by adamjonas** [comment]
> If there are no objections, I'll open a PR to bucket the others.

no objections

**Pull request merged**
