### PR TITLE
Add coinjoin-done-right:-the-onchain-offchain-mix-and-anti-sybil-with-riddles to bitcoinplusplus/onchain-privacy

### PR DESCRIPTION
**Pull request by delcin-raj**
This PR adds [Coinjoin Done Right: the onchain offchain mix, and anti Sybil with Riddles](https://www.youtube.com/watch?v=khmLiM9xhwk) transcript to the bitcoinplusplus/onchain-privacy directory.

### CODE REVIEW

**Comment by delcin-raj** [comment]
Hi,I have not completed the review. I need some time to do this properly.
Please give me another 24 hours to finish this. I have already put like 4 hours into this (to understand the topics clearly).
I created the PR because my time is about to expire.

**Comment by kouloumos** [comment]
> Hi,I have not completed the review. I need some time to do this properly. Please give me another 24 hours to finish this. I have already put like 4 hours into this (to understand the topics clearly). I created the PR because my time is about to expire.

Ok @delcin-raj! Thank you for putting the time - understanding the topic through reviewing is exactly what we want.

**Comment by delcin-raj** [comment]
I'm unable to resubmit my changes. Fork and create pr step is failing.

**Comment by kouloumos** [comment]
@Extheoisah can you check this?

**Comment by delcin-raj** [comment]
image

**Comment by 0tuedon** [comment]
> @delcin-raj Can you send a screenshot of the issue?
> 
> @0tuedon can you check this?

Okay, checking out.

**Comment by 0tuedon** [comment]
> @delcin-raj Can you send a screenshot of the issue?
> 
> @0tuedon can you check this?

i can't quite grasp what the issue is, maybe a merge conflict issue i suppose?

**Comment by Extheoisah** [comment]
@delcin-raj We're looking into the issue. Please can we get you on a discord chat to understand and assist you with the issue?

**Comment by Extheoisah** [comment]
> My discord username: delcin

Thanks sent you a friend request.

**Comment by kouloumos** [comment]
@delcin-raj We're facing an ongoing issue with resubmitting via the website. We are working on it and we'll notify you once it's resolved. Once fixed, you'll be able to resubmit your work.

As a workaround, you might consider editing the transcript using the [github.dev editor](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor) and manually committing your changes. If you choose this approach, please let us know if you encounter any challenges or issues along the way

**Comment by delcin-raj** [comment]
Committed the review.
Please take a look.

**Comment by kouloumos** [comment]
Hey @delcin-raj! Fantastic job! You really put the effort to strike a balance between completeness and readability and this is greatly appreciated! Thank you! The addition of chapters and the removal of unnecessary discussions really made a difference! Considering the length of this transcript, this is the best editing that I've seen since we started this project! 

That said, this needs a bit more work before is ready to merge. To assist with these necessary improvements, I've pushed a demo-fixup commit (I've done all the necessary edits up until the "Centrally coordinated smooth experience. Can't choose amount" section) and provided detailed feedback notes that can benefit both this submission and your future reviews.

Before delving into the feedback, I'd like to mention that our reviewing pipeline is relatively new, and we're continuously exploring ways to enhance productivity for all involved. I recently realized the substantial advantages of having each sentence on a separate line while reviewing, especially for comparing the before and after versions. Consequently, you'll notice numerous changes in my demo-fixup commit; I reformatted the submission to one sentence per line to streamline the review process. I intend to implement this format for all transcripts at reviews.btctranscripts.com, aiming to facilitate future reviews, including yours.

**Feedback for you**

- Date of original presentation: Make sure that the date is accurate. In this case the date was taken directly from the upload date of the YouTube video, therefore is not the date of the original presentation. Sometimes you might need to make some extra effort to find the date - in this case, you could find the original date by clicking [the link](https://bitcoincdmx2022.sched.com/event/1Ewjx/coinjoin-done-right-the-onchainoffchain-mix-and-anti-sybil-with-riddles) in the video description. 
- I've moved the note about the slides at the top of the document.
- Headings: The title of the transcript is always rendered as H1 (# Title), so always start with H2 (## Heading2). Also, for readability, always leave an empty line after each heading.
- If you compare your introduction vs my changes you will observe that you removed the part that was setting the tone for the whole transcript, which was important. The overview of the talk is not needed if you are using Headings correctly, as the reader can see the outline through the Headings at the sidebar. Other than that, I didn't observe any excessive editing. 
- There is no need to create list when writing the content. Do that only if the speaker explicitly does that.
- If you are referring to slides in the presentation, there is no need to type out the content of the slide as you did for CoinJoin XT > Example 1 > Illustration. Just add a reference to the specific slide at an appropriate point.
- When an occasional speaker interjects briefly into the conversation, you can seamlessly integrate their contributions within the main speaker's dialogue. Use square brackets to denote the remarks of the infrequent speaker ensuring the flow and coherence of the transcript. This also helps avoiding the  ""Adam Gibson continues ..." lines. 
- Transcription style: Reviewers should strive for an "edited transcription" style, which can also be referred to as clean verbatim transcription. The goal of an edited transcription is to preserve the meaning of a text without paraphrasing. Stammering, filler words such as 'like' or 'you know', and unnecessary non-verbal communication can be omitted. Strike a balance between completeness and readability. You done that exceptionally well, but there is room for improvements. I've gather some examples from my demo-fixup to help you understand what kind of edits you can do:
  - "If you let your impatience get the better of you, you've got a very good chance of losing your money or ~perhaps~ perhaps not losing your money and then just ~being very~ having very bad privacy as well which is obviously the topic of this conference."
  - "So, ~you know you~ you got to be sensible about these things"
  - "On the other hand ~if we're talking about~ if we're talking about something like lightning we could say it's not a political act."
  - "~I think I put that on this slide or maybe the next one anyway didn't but but but I would say you know making a lightning payment is not a political act~ maybe that's a weird thing to say **,** like if I make a payment with on-chain Bitcoin it's a political act **,** if I make a payment with lightning it's not **.** I can't 100% defend that position but maybe it gets your brain thinking about these issues."
  - "But I think Peter Todd at the back of the room here is one of many people who pointed out before the event, and of course he was involved in the creation of Zcash, ~He pointed out before the event~ that this is a fundamental kind of failure mode you have in such a system which is unavoidable no matter how good your cryptography is claimed to be."
  - "The problem is in the flow from the brain of an academic to a paper, to an engineer, to another engineer, mistakes get made ~.
You know,~ in building these systems ~,~ **. T**hey are intrinsically very difficult to build."
  - "~Anyway, so~ CoinJoin, as I said earlier, is the way we're tending to do things. ~And we've got, you know,~ let's even forget about join market for a minute."
  - "People have this idea that ~, and I think I might have, yeah, this idea of~ make every spend~er~ **a** CoinJoin is somehow the ideal."
  - "~Put it this way, does anyone agree, no, I have to put it this way around,~ does anyone disagree with this statement, and if so, why?" (mid-sentence rephrasing)
  - "There's obviously lots of answers to that, ~but I wanted to,~ this is debatable, but I wanted to illustrate what I think is how it's working today, which is that people are using CoinJoin mostly in these systems." (mid-sentence rephrasing)
  - Lines like "I think I got another answer there, yeah." or "I mean, feel free to offer any other answers if you have any, no?" could be removed completely without affecting the completeness of the transcript.
  
Thanks again @delcin-raj! I believe that after another pass this will be ready to merge!

**Comment by delcin-raj** [comment]
I will finish this today.

**Comment by delcin-raj** [comment]
Have committed the changes. Please take a look

**Comment by kouloumos** [comment]
Thank you for your contribution @delcin-raj! A transcript packed with a lot of insides but its dependency on the slides definitely made editing challenging. I hope that you learn something out of this! 

Apart from various edits that I did, the only feedback that I have is for tags. When tagging the content, consider adding relevant tags that best describe the transcript's content. As the reviewer, you're well-placed to understand the nuanced topics discussed. Accurate tagging is crucial as it significantly aids in content discovery, helping others find relevant information more easily.
You can see all my fixups by looking at [this commit](https://github.com/bitcointranscripts/bitcointranscripts/pull/314/commits/8e24426405de18d884a12d560e08574cefba52e1) - I hope that they will be helpful.

Hopefully we will see more transcripts from you in the future!

If you haven't done that already, [We'd love to hear your feedback](https://cryptpad.fr/form/#/2/form/view/3P2CsohsHOkcH7C+WdtX0-tvqjBHqXnAmz5D9yx0e04/) for this project and your experience as a reviewer (anonymously) as we are trying to improve and make the experience better for all.

**Pull request merged**
